$(function(){
    var bttn_next = $("#next_page_button");
    var bttn_prev = $("#prev_page_button");
    $("#mybook").booklet({
        name:               $name,
        width:              $width,
        height:             $height,
        speed:              $speed,
        direction:          $direction,
        startingPage:       $startingPage,
        easing:             $easing,
        easeIn:             $easeIn,
        easeOut:            $easeOut,
        closed:             $closed,
        closedFrontTitle:   $cFrontTitle,
        closedFrontChapter: $cFrontChapter,
        closedBackTitle:    $cBackTitle,
        closedBackChapter:  $cBackChapter,
        covers:             $covers,
        autoCenter:         $autoCenter,
        pagePadding:        $pagePadding,
        pageNumbers:        $pageNumbers,
        pageBorder:         $pageBorder,
        manual:             $manual,
        hovers:             $hovers,        
        hoverWidth:         $hoverWidth,
        hoverSpeed:         $hoverSpeed,
        hoverTreshold:      $hoverTreshold,
        hoverClick:         $hoverClick,        
        overlays:           $overlays,
        tabs:               $tabs,
        tabWidth:           $tabWidth,
        tabHeight:          $tabHeight,
        nextControlText:    $nextControlText,
        previousControlText: $previousControlText,
        nextControlTitle:   $nextControlTitle,
        previousControlTitle: $previousControlTitle,
        arrows:             $arrows,
        arrowsHide:         $aHide,
        cursor:             $cursor,
        hash:               $hash,
        hashTitleText:      $hTitleText,
        next:               $next,
        prev:               $prev, 
        auto:               $auto,
        delay:              $delay,
        pause:              $pause,
        play:               $play,
        menu:               $menu,
        pageSelector:       $pageSelector,
        chapterSelector:    $chapterSelector,
        shadows:            $shadows,
        shadowTopFwdWidth:  $shadowTopFwdWidth,
        shadowTopBackWidth: $shadowTopBackWidth,
        shadowBtmWidth:     $shadowBtmWidth
    });
    bttn_next.show();
    bttn_prev.show();
});

